name: Hyperplex
url: http://hyperplex.co
description: A blog by Daniel Aditya Istyana which will talk about technology and news arounds Apple. Sometimes you've nothing to read here and of course it leads nowhere.
permalink: /:categories/:year/:month/:title/
category_dir: /categories/
paginate: 10
highlighter: pygments
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', '_glynn.yml', 'env', 'production.sh']
instagram_cache: true
instagram_cache_directory: .instagram_cache
gems: ['jekyll-twitter-plugin', 'jekyll-sitemap']
